language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    allow_failures:
        - php: hhvm
before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script: ./vendor/bin/phpunit
